### ISSUE TITLE
CRS Roadmap

### ISSUE THREAD

**Issue by clegendre** [Invenietis/crs#1]
- [x] Target NetStandard 2.0
- [x] Command response dispatcher raw websockets implementation that does not relies on SignalR
- [x] Revisits the CRS pipeline: implementation will be based on AspNetCore.
- [x] Revists CRS configuration: 

1. Configure AmbientValues
2. Configure Requests (Commands and Events),
3. Configure Endpoints

- [x] Removes Engine / Receiver projects. Implementations of command processor will be provided by plugins
- [x] Allow plugins to be registered as a CRS component during Crs configuration
- [x]  ~~External messaging: Implements CK.Crs.Brighter plugin based on Paramore.Brighter .~~
- [x] Crs model description
- [x] Integrates CK.ActivityMonitor.SimpleSender
- [x] External messaging: Implements CK.Crs.Rebus plugin based on Rebus
- [x] SignalR Core implementation
- [x]  Moves AmbientValues to their own library and abstractions.
- [ ]  Command batching
- [ ]  Command scheduling
- [ ]  Command and event store (at least abstractions)
- [ ] ~~Explicit event registration: #7~~
- [ ]  Unit tests, unit tests, unit tests
